[package]
name = "ni-fpga-macros"
version = "0.1.0"
authors = ["Connor Worley <connorbworley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ni-fpga-derive = { path = "../ni-fpga-derive" }
packed_struct = "0.3.0"
packed_struct_codegen = "0.3.0"
